name: Suricata rule update

on:
  schedule:
    - cron: "0 2 * * *" # Run at every 2am
  workflow_dispatch:

jobs:
  run-python-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------
      # Install Suricata
      # ---------------------------
      - name: Install Suricata
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:oisf/suricata-stable -y
          sudo apt-get update
          sudo apt-get install -y suricata

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate venv and install requirements
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python update script
        env:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
        run: |
          source venv/bin/activate
          sudo python main.py
